services:
  db:
    image: postgis/postgis:18-3.6
    restart: always
    user: postgres
    env_file: ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    expose:
      - 5432
    ports:
      - 5432:54320
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

volumes:
  pgdata:
networks:
  net:
    driver: bridge